 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: metabase-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: metabase.local
     http:
       paths:
       - path: /
         pathType: Prefix
         backend:
           service: 
            name: metabase
            port: 
              number: 3000