apiVersion: apps/v1
kind: Deployment
metadata: 
  name: metabase
spec: 
  progressDeadlineSeconds: 600
  replicas: 2
  selector: 
    matchLabels: 
      app: metabase
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: metabase
    spec: 
      containers: 
        - 
          image: metabase/metabase:latest
          imagePullPolicy: IfNotPresent
          name: metabase
          ports: 
            - 
              containerPort: 5432
              protocol: TCP
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              value: metabase
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mbuser
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mbpass
                  key: MB_DB_PASS
            - name: MB_DB_HOST
              value: postgres