apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pgadmin
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: pgadmin
  template: 
    metadata: 
      labels: 
        app: pgadmin
    spec: 
      containers: 
        - 
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          name: pgadmin
          ports: 
            - 
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgmail
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: PGADMIN_DEFAULT_EMAIL