apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec: 
  progressDeadlineSeconds: 600
  replicas: 2
  selector: 
    matchLabels: 
      app: postgres
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      volumes:
        -
          name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-db
      containers: 
        - 
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          name: postgres-secrets
          ports: 
            - 
              containerPort: 3000
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresuser
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespass
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: metabase

